In [62]:
import tensorflow as tf
from tensorflow.keras.layers import Layer, Dense

In [76]:
a = Dense(5,     kernel_initializer="zeros", bias_initializer="glorot_uniform", input_dim=4)
a.weights

[]

In [77]:
a(tf.ones((2,3,4)))

<tf.Tensor: shape=(2, 3, 5), dtype=float32, numpy=
array([[[-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ],
        [-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ],
        [-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ]],

       [[-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ],
        [-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ],
        [-0.43096846, -0.41633087,  0.6679013 ,  0.21747267,
         -0.5232843 ]]], dtype=float32)>

In [67]:
tf.ones((2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [79]:
a.weights[0]

<tf.Variable 'dense_8/kernel:0' shape=(4, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [80]:
128*9+1

1153

In [37]:
class SimpleDense(Layer):

    def __init__(self, units=32):
        super(SimpleDense, self).__init__()
        self.units = units

    def build(self, input_shape):  # Create the state of the layer (weights)
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_shape[-1], self.units),
                                 dtype='float32'),
            trainable=False)
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(self.units,), dtype='float32'),
            trainable=False)
        print('built')

    def call(self, inputs):  # Defines the computation from inputs to outputs
        return tf.matmul(inputs, self.w) + self.b




In [38]:
linear_layer = SimpleDense(4)

In [39]:
# This will also call `build(input_shape)` and create the weights.
y = linear_layer(tf.ones((2, 2)))
assert len(linear_layer.weights) == 2

built


In [40]:
len(linear_layer.trainable_weights)

0

In [41]:
y = linear_layer(tf.ones((2, 2)))

In [42]:
linear_layer.trainable

True

In [22]:
linear_layer.trainable_weights

[<tf.Variable 'simple_dense_2/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.03930287,  0.03224061, -0.0179645 ,  0.02024974],
        [ 0.06378732, -0.02854596, -0.01284947, -0.03777556]],
       dtype=float32)>,
 <tf.Variable 'simple_dense_2/Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [56]:
d = tf.keras.layers.Dense(10)

In [57]:
d(tf.ones(shape=(2, 2))).numpy()

array([[ 0.2122589 , -0.17327732,  0.84268475,  0.40460068, -1.003344  ,
         0.39375657,  0.84750175,  0.73829997,  0.11632788,  0.7789558 ],
       [ 0.2122589 , -0.17327732,  0.84268475,  0.40460068, -1.003344  ,
         0.39375657,  0.84750175,  0.73829997,  0.11632788,  0.7789558 ]],
      dtype=float32)

In [46]:
d.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 10) dtype=float32, numpy=
 array([[ 0.58361095, -0.69991755, -0.23771867, -0.30592373,  0.6092015 ,
          0.539126  ,  0.15861529,  0.16391957, -0.45337498, -0.16455394],
        [ 0.08602393,  0.38544315, -0.06850648,  0.31714088, -0.0438956 ,
         -0.6263885 ,  0.06883997, -0.31476498,  0.43495744, -0.3391663 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [47]:
d.kernel

<tf.Variable 'dense/kernel:0' shape=(2, 10) dtype=float32, numpy=
array([[ 0.58361095, -0.69991755, -0.23771867, -0.30592373,  0.6092015 ,
         0.539126  ,  0.15861529,  0.16391957, -0.45337498, -0.16455394],
       [ 0.08602393,  0.38544315, -0.06850648,  0.31714088, -0.0438956 ,
        -0.6263885 ,  0.06883997, -0.31476498,  0.43495744, -0.3391663 ]],
      dtype=float32)>

In [48]:
d.bias

<tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [60]:
d = tf.keras.layers.Dense(10)
inputs = tf.keras.Input(shape=(10,))

In [61]:
d(inputs).numpy()

AttributeError: 'Tensor' object has no attribute 'numpy'